<a href="https://colab.research.google.com/github/Elsamariatomlin/elsa/blob/main/elsapython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a =np.random.rand()
print(a)
b=np.random.rand(3)
print(b)
arr =np.array([1,2,4,3])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
x=np.random.randint(1,10)
print(x)
y=np.random.randint(0,100,size=5)
print(y)
z=np.random.randint(10,100,size=(3,3))
print(z)
otp = np.random.randint(100000, 1000000, size=5)
print( otp)
otp4 = np.random.randint(1000, 10000)
print(otp4)


0.65798975502288
[0.18140273 0.2538983  0.57618277]
2.5
2.5
1.118033988749895
6
[88 84 75 84 41]
[[80 89 39]
 [66 15 11]
 [79 25 12]]
[944449 279552 208360 574778 942254]
9465


In [ ]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)
#series
#Dataframe
data={"name":["alice",'bob'],"age":[25,20]}
df=pd.DataFrame(data)
print(df)


0    10
1    20
2    30
3    40
dtype: int64
    name  age
0  alice   25
1    bob   20


In [ ]:
import pandas as pd
#df.head
data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,86,75,96]
}
df=pd.DataFrame(data1)
print(df.head())
print(df.head(3))


     name  score
0   najah     85
1    elsa     96
2  bhadra     86
3   david     75
4    rusu     96
     name  score
0   najah     85
1    elsa     96
2  bhadra     86


In [ ]:
#d.tail
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,86,75,96]
}
df=pd.DataFrame(data1)
print(df.tail())
print(df.tail(3))

     name  score
0   najah     85
1    elsa     96
2  bhadra     86
3   david     75
4    rusu     96
     name  score
2  bhadra     86
3   david     75
4    rusu     96


In [ ]:
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,86,75,96],
    "grade":['a','b','c','d','e']
}
df=pd.DataFrame(data1)
df.info()
df.describe()
print(df.columns)
print(df.shape)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    5 non-null      object
 1   score   5 non-null      int64 
 2   grade   5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
Index(['name', 'score', 'grade'], dtype='object')
(5, 3)


In [ ]:
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,86,75,96],
    "grade":['a','b','c','d','e']
}

Index(['name', 'score', 'grade'], dtype='object')
(5, 3)


In [73]:
#def.loc[]
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,86,75,96],
    "grade":['a','b','c','d','e']
}
df = pd.DataFrame(data1)

print(df.loc[0,'grade'])
print(df.loc[1,'name'])
print(df.loc[:,["name","score"]])

a
elsa
     name  score
0   najah     85
1    elsa     96
2  bhadra     86
3   david     75
4    rusu     96


In [75]:
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,86,75,96],
    "grade":['a','b','c','d','e']
}
df = pd.DataFrame(data1)
df.iloc[0]
df.iloc[0,1]
df.iloc[:,[0,2]]

name grade
0   najah     a
1    elsa     b
2  bhadra     c
3   david     d
4    rusu     e

In [78]:
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,None,75,96],
    "grade":['a','b','c','d','e']
}
df = pd.DataFrame(data1)
print(df.isnull())

    name  score  grade
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4  False  False  False


In [79]:
#df.dropna()  null delete akkum
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,None,75,96],
    "grade":['a','b','c','d','e']
}
df = pd.DataFrame(data1)
print(df.dropna())

    name  score grade
0  najah   85.0     a
1   elsa   96.0     b
3  david   75.0     d
4   rusu   96.0     e


In [81]:
import pandas as pd

data1={
    "name":['najah',"elsa","bhadra","david","rusu"],
    "score":[85,96,None,75,96],
    "grade":['a','b','c','d','e']
}
df = pd.DataFrame(data1)
print(df.fillna(81))

     name  score grade
0   najah   85.0     a
1    elsa   96.0     b
2  bhadra   81.0     c
3   david   75.0     d
4    rusu   96.0     e
